return {
    PlaceObj('ModItemCode', { 'name', "fl_config", 'CodeFileName', "Code/fl_config.lua" }),
    PlaceObj('ModItemCode', { 'name', "fl_debug", 'CodeFileName', "Code/fl_debug.lua" }),
    PlaceObj('ModItemCode', { 'name', "fl_state", 'CodeFileName', "Code/fl_state.lua" }),
    PlaceObj('ModItemCode', { 'name', "fl_hydrology", 'CodeFileName', "Code/fl_hydrology.lua" }),
    PlaceObj('ModItemCode', { 'name', "fl_save", 'CodeFileName', "Code/fl_save.lua" }),
    PlaceObj('ModItemCode', { 'name', "fl_terrain", 'CodeFileName', "Code/fl_terrain.lua" }),
    PlaceObj('ModItemCode', { 'name', "fl_water", 'CodeFileName', "Code/fl_water.lua" }),
    PlaceObj('ModItemCode', { 'name', "fl_rain", 'CodeFileName', "Code/fl_rain.lua" }),
    PlaceObj('ModItemCode', { 'name', "fl_climate", 'CodeFileName', "Code/fl_climate.lua" }),
    PlaceObj('ModItemCode', { 'name', "fl_buildings", 'CodeFileName', "Code/fl_buildings.lua" }),
    PlaceObj('ModItemCode', { 'name', "fl_dust", 'CodeFileName', "Code/fl_dust.lua" }),
    PlaceObj('ModItemCode', { 'name', "fl_vehicles", 'CodeFileName', "Code/fl_vehicles.lua" }),
    PlaceObj('ModItemCode', { 'name', "fl_shuttles", 'CodeFileName', "Code/fl_shuttles.lua" }),
    PlaceObj('ModItemCode', { 'name', "fl_trains", 'CodeFileName', "Code/fl_trains.lua" }),
    PlaceObj('ModItemCode', { 'name', "fl_colonists", 'CodeFileName', "Code/fl_colonists.lua" }),
    PlaceObj('ModItemCode', { 'name', "fl_groundwater", 'CodeFileName', "Code/fl_groundwater.lua" }),
    PlaceObj('ModItemCode', { 'name', "fl_soil", 'CodeFileName', "Code/fl_soil.lua" }),
    PlaceObj('ModItemCode', { 'name', "fl_construction", 'CodeFileName', "Code/fl_construction.lua" }),
    PlaceObj('ModItemCode', { 'name', "fl_ui", 'CodeFileName', "Code/fl_ui.lua" }),
    PlaceObj('ModItemCode', { 'name', "fl_lifecycle", 'CodeFileName', "Code/fl_lifecycle.lua" }),
    PlaceObj('ModItemCode', { 'name', "Flood", 'CodeFileName', "Code/Flood.lua" }),
}
