return PlaceObj('ModDef', {
    'title', "Flood",
    'id', "Flood",
    'author', "fredware",
    'version', 7,
    'lua_revision', 350453,
    'saved_with_revision', 405907,
    'description', "Rain fills terrain depressions with water. Catchments fill, spill and merge; evaporation and infiltration drain the water. Toxic rain adds a persistent yellow-green contaminant; fresh water is blue and dilutes it.\n\nEffects (each can be switched off in Code/fl_config.lua):\n- Evaporation follows the terraformed climate: thin, cold air empties puddles fast.\n- Outdoor buildings under deep water stop working; shallow water wears them. Building on flooded ground is blocked or warned.\n- Rain washes accumulated dust off everything that collects it; toxic rain corrodes outdoor buildings.\n- Fresh water soaking in recharges nearby underground water deposits.\n- Toxic water and dried toxic residue degrade soil locally; fresh water improves it.\n- Rovers slow in deep water and can break down past their fording depth. Drones fly slower in rain, lose battery in deep water and gather toxic grime. Shuttles slow in rain and are grounded in heavy storms. Trains crawl over flooded rails.\n- Ice: when it freezes (unterraformed planet, cold waves, cold areas) puddles and lakes get a solid surface that rovers, drones and colonists cross on top of.\n- Colonists in the open: toxic rain stresses them (and harms them once the air is breathable), toxic water burns skin, deep water exhausts them and water over their head can drown them; fresh rain under an open sky lifts their mood.\n\nTemporary controls: Light, Moderate and Heavy toggle test storms; Fresh/Toxic switches rain type. Click an active strength again to stop. Test rain uses 10x precipitation so filling is visible sooner; gameplay effects use the normal storm rate. These are real storms with normal game effects.\n\nStandalone mod using the native terrain-water approach of Martian Waters. Terrain sampling defaults to 4 metres and becomes coarser on very large maps. Smaller holes may be missed. Its only asset is an ice plate mesh copied from Martian Waters; no dependency on Martian Waters.",
    'short_description', "Rainfall, puddles, lakes, toxic water, and their effects on buildings, vehicles, soil and colonists.",
    'last_changes', "No more stutter: all of Flood's background work (water steps, depth updates, lake redraws, ice, colours, soil, terrain rebuilds) now shares one small real-time budget (8 ms every 50 ms) at any game speed, and the water step and soil pass run in short slices; rain on dry ground is computed per basin. Saves: a save made without Flood loads with Flood and starts dry; a save made with Flood loads cleanly after Flood is switched off or removed (no Flood objects, suspended buildings or speed modifiers are saved). The test Cold Wave button now runs timed cold waves, renewed while it is on. The panel shows Flood's slowest step.",
    'entities', {
        "FL_IcePlate",
    },
    'code', {
        "Code/fl_config.lua",
        "Code/fl_entity_data.lua",
        "Code/fl_debug.lua",
        "Code/fl_diagnostics.lua",
        "Code/fl_state.lua",
        "Code/fl_hydrology.lua",
        "Code/fl_save.lua",
        "Code/fl_terrain.lua",
        "Code/fl_water.lua",
        "Code/fl_rain.lua",
        "Code/fl_climate.lua",
        "Code/fl_buildings.lua",
        "Code/fl_dust.lua",
        "Code/fl_vehicles.lua",
        "Code/fl_shuttles.lua",
        "Code/fl_trains.lua",
        "Code/fl_colonists.lua",
        "Code/fl_groundwater.lua",
        "Code/fl_soil.lua",
        "Code/fl_construction.lua",
        "Code/fl_ice.lua",
        "Code/fl_terraforming.lua",
        "Code/fl_cold_wave.lua",
        "Code/fl_ui.lua",
        "Code/fl_lifecycle.lua",
        "Code/Flood.lua",
    },
    'has_data', true,
    'TagGameplay', true,
})
